# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crud.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def clear(self):
        self.lineEdit_name.setText('')
        self.lineEdit_address.setText('')
        self.lineEdit_contact.setText('')
        self.lineEdit_email.setText('')

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 531)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(30, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_delete = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(190, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_delete.setFont(font)
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.pushButton_update = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_update.setGeometry(QtCore.QRect(110, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_update.setFont(font)
        self.pushButton_update.setObjectName("pushButton_update")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(270, 390, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        ###
        self.pushButton_clear.clicked.connect(self.clear)
        ###
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name.setGeometry(QtCore.QRect(162, 110, 181, 31))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.label_controlpanel = QtWidgets.QLabel(self.centralwidget)
        self.label_controlpanel.setGeometry(QtCore.QRect(110, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_controlpanel.setFont(font)
        self.label_controlpanel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_controlpanel.setObjectName("label_controlpanel")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        self.label_name.setGeometry(QtCore.QRect(40, 110, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_name.setFont(font)
        self.label_name.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_name.setObjectName("label_name")
        self.lineEdit_address = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_address.setGeometry(QtCore.QRect(160, 170, 181, 31))
        self.lineEdit_address.setObjectName("lineEdit_address")
        self.label_address = QtWidgets.QLabel(self.centralwidget)
        self.label_address.setGeometry(QtCore.QRect(38, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_address.setFont(font)
        self.label_address.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_address.setObjectName("label_address")
        self.lineEdit_contact = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_contact.setGeometry(QtCore.QRect(162, 230, 181, 31))
        self.lineEdit_contact.setObjectName("lineEdit_contact")
        self.label_contact = QtWidgets.QLabel(self.centralwidget)
        self.label_contact.setGeometry(QtCore.QRect(40, 230, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_contact.setFont(font)
        self.label_contact.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_contact.setObjectName("label_contact")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(162, 290, 181, 31))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(40, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_email.setFont(font)
        self.label_email.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_email.setObjectName("label_email")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(370, 40, 321, 431))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Gym Management System"))
        self.pushButton_add.setText(_translate("MainWindow", "ADD"))
        self.pushButton_delete.setText(_translate("MainWindow", "DELETE"))
        self.pushButton_update.setText(_translate("MainWindow", "UPDATE"))
        self.pushButton_clear.setText(_translate("MainWindow", "CLEAR"))
        self.label_controlpanel.setText(_translate("MainWindow", "Control Panel"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_address.setText(_translate("MainWindow", "Address:"))
        self.label_contact.setText(_translate("MainWindow", "Contact:"))
        self.label_email.setText(_translate("MainWindow", "Email ID:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

